version: "3.9"
services:
  # First IoT device
  device1:
    image: "davidetestoni/iotdevice:latest"
    environment:
      - DEVICE_NAME=Sensor_1
      - DEVICE_SLEEP=10000
    links:
      - rabbitmq
      
  # Second IoT device
  device2:
    image: "davidetestoni/iotdevice:latest"
    environment:
      - DEVICE_NAME=Sensor_2
      - DEVICE_SLEEP=8000
    links:
      - rabbitmq

  # Data controller
  datacontroller:
    image: "davidetestoni/datacontroller:latest"
    links:
      - rabbitmq
    external_links:
      - mysql

  # Data provider
  dataprovider:
    image: "davidetestoni/dataprovider:latest"
    links:
      - redis
    external_links:
      - mysql

  # Rabbit MQ (service bus)
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  # Redis (cache)
  redis:
    image: "redis"
    ports:
      - "6379:6379"

networks:
    default:
        external:
            name: iot