version: "3.9"
services:
  # First IoT device
  device1:
    image: "davidetestoni/iotdevice:latest"
    environment:
      - DEVICE_NAME=Sensor_1
      - DEVICE_SLEEP=1000
    links:
      - rabbitmq
      
  # Second IoT device
  device2:
    image: "davidetestoni/iotdevice:latest"
    environment:
      - DEVICE_NAME=Sensor_2
      - DEVICE_SLEEP=800
    links:
      - rabbitmq

  # Data controller
  datacontroller:
    image: "davidetestoni/iotdatacontroller:latest"
    links:
      - rabbitmq
    external_links:
      - mysql

  # Data provider
  dataprovider:
    image: "davidetestoni/iotdataprovider:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - "3000:3000"
      - "6390:6390"
    links:
      - redis
      - rabbitmq
    external_links:
      - mysql

  # Admin Client
  admin-client:
    image: "davidetestoni/iotclient:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - "4000:4000"
    links:
      - dataprovider

  # Signer Client
  signer-client:
    image: "davidetestoni/iotclient:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - "4001:4000"
    links:
      - dataprovider

  # Rabbit MQ (service bus)
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  # Redis (cache)
  redis:
    image: "redis"
    ports:
      - "6379:6379"

networks:
    default:
        external:
            name: iot