version: "3.9"
services:
  device1:
    image: "davidetestoni/iotdevice:latest"
    environment:
      - DEVICE_NAME=Sensor_1
      - DEVICE_SLEEP=10000
    links:
      - rabbitmq
  device2:
    image: "davidetestoni/iotdevice:latest"
    environment:
      - DEVICE_NAME=Sensor_2
      - DEVICE_SLEEP=8000
    links:
      - rabbitmq
  datacontroller:
    image: "davidetestoni/datacontroller:latest"
    links:
      - rabbitmq
    external_links:
      - mysql
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
    default:
        external:
            name: iot